### ISSUE TITLE
[问题]: skinsrestorer更新了apitr还是用的旧的

### ISSUE THREAD

**Issue by huanym** [TrPlugins/TrMenu#376]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: windows 10
  | Server software: purpur-1.18.2-1612
  | Java version: 16

  | TabooLib: x.x.x
  | TrMenu: 3.1.1.11

### 🔍 详细的描述


1.  skinsrestorer更新了apitr还是用的旧的
每当玩家进游戏就会报错刷屏一次

### 🗄 服务端日志

https://paste.fastmirror.net/?6dd8ee6adb7e4d50#B8vywFERnSzLy8g37vtbYDXsedNYnYQ3XFvRGXFgLUQv

https://paste.fastmirror.net/?e6fcf4bfb1021367#A5f8L57MpPS1st3nboq5UWenW4Q9gQTgWmjtP9nCgGvT


### ⚙ 配置文件

```

```

**Comment by ArubikU** [comment]
i have the same erro :(

**Comment by CCBlueX666** [comment]
我也出现了类似的问题，更多信息 https://github.com/TrPlugins/TrMenu/issues/377

**Comment by huanym** [comment]
`[15:12:25 WARN]: [TrMenu] Plugin TrMenu v3.1.11 generated an exception while executing task 1523526
java.lang.ClassCastException: class net.skinsrestorer.bukkit.utils.BukkitProperty cannot be cast to class com.mojang.authlib.properties.Property (net.skinsrestorer.bukkit.utils.BukkitProperty is in unnamed module of loader '[S][皮肤]SkinsRestorer.jar' @143747cb; com.mojang.authlib.properties.Property is in unnamed module of loader java.net.URLClassLoader @5eb5c224)
        at me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:31) ~[[T][菜单]TrMenu-3.1.11.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77) ~[[T][菜单]TrMenu-3.1.11.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47) ~[[T][菜单]TrMenu-3.1.11.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:21) ~[[T][菜单]TrMenu-3.1.11.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:19) ~[[T][菜单]TrMenu-3.1.11.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) ~[[T][菜单]TrMenu-3.1.11.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1612]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by huanym** [comment]
`[22:43:56 WARN]: java.lang.ClassCastException: class net.skinsrestorer.bukkit.utils.BukkitProperty cannot be cast to class com.mojang.authlib.properties.Property (net.skinsrestorer.bukkit.utils.BukkitProperty is in unnamed module of loader '[S][皮肤]SkinsRestorer.jar' @76ee1ccd; com.mojang.authlib.properties.Property is in unnamed module of loader java.net.URLClassLoader @5eb5c224)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:31)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.util.bukkit.Heads.getHead(Heads.kt:40)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.texture.Texture.generate(Texture.kt:41)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.api.menu.IItem$DefaultImpls.generate(IItem.kt:22)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.item.Item.generate(Item.kt:16)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.item.Item.build(Item.kt:39)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:34)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:31)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:156)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:85)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:155)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.Menu.page(Menu.kt:123)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.api.action.impl.menu.Page.onExecute(Page.kt:26)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:93)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:91)
[22:43:56 WARN]:        at [T][菜单]TrMenu-3.1.11.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$7.run(BukkitExecutor.kt:98)
[22:43:56 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[22:43:56 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:43:56 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1558)
[22:43:56 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[22:43:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1482)
[22:43:56 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[22:43:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[22:43:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:43:56 INFO]: ICON: I`

**Comment by CCBlueX666** [comment]
https://github.com/TrPlugins/TrMenu/issues/376#issuecomment-1166526024

**Comment by Arasple** [comment]
[CI #73](https://github.com/TrPlugins/TrMenu/actions/runs/2601433317)
