### ISSUE TITLE
疑似与SkinRestorer不兼容报错

### ISSUE THREAD

**Issue by CCBlueX666** [TrPlugins/TrMenu#377]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-06-26 20:51:28)

  | Server OS: Debian 4.19.208-1 (2021-09-29) 4.19.0-18-amd64
  | Server software: git-Paper-379 (MC: 1.18.2)
  | Java version: Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)

  | TabooLib: 未安装
  | TrMenu: 3.1.12
Installed Plugins:
  · SkinRestorer - 14.2.1
```

### 🔍 详细的描述

```
1. 使用上述版本
2. 加入新玩家（无论是否第一次/是否正版加入服务器）
3. 检查控制台报错
```

### 🗄 服务端日志

```
[TrMenu] Plugin TrMenu v3.1.12 generated an exception while executing task 24068351
java.lang.ClassCastException: class net.skinsrestorer.bukkit.utils.BukkitProperty cannot be cast to class com.mojang.authlib.properties.Property (net.skinsrestorer.bukkit.utils.BukkitProperty is in unnamed module of loader 'SkinsRestorer.jar' @37ce5a9d; com.mojang.authlib.properties.Property is in unnamed module of loader java.net.URLClassLoader @5c29bfd)
        at me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:31) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:21) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:19) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) ~[TrMenu-3.1.12.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-386]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-386]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
```

### ⚙ 配置文件

```
Options:
  # High, Normal, Low
  Running-Performance: Normal
  Multi-Thread: true
  Async-Load-Menus: true

Database:
  # Local: SQLITE
  # External: SQL, MONGODB
  Method: SQL
  Type:
    SQLite:
      file-name: data
      table: npc
    SQL:
      host: localhost
      port: XXXX
      user: XXXX
      password: XXXX
      database: XXXX
      table: XXXX
    MongoDB:
      client: 'mongodb://localhost:3307'
      database: trixey
      collection: trplugins.menu
  Index:
    # UUID, USERNAME
    Player: USERNAME

Loader:
  Menu-Files:
    - 'plugins/CustomMenusFolder'

Menu:
  Settings:
    Bound-Item-Interval: 2000
  Icon:
    Inherit: false
    Item:
      Default-Name-Color: "&7"
      Default-Lore-Color: "&7"
      Pre-Color: false

Action:
  Inputer:
    Cancel-Words:
      - 'cancel|quit|end'
      - 'q'
  Kether:
    Allow-Tolerance-Parser: false


Shortcuts:
  Offhand: [ ]
  Sneaking-Offhand:
    - condition: 'perm *trmenu.shortcut'
      execute: 'open: Example'
      deny: 'return'
  Right-Click-Player: 'open: Profile'
  Sneaking-Right-Click-Player: [ ]
  PlayerInventory-Border-Left: [ ]
  PlayerInventory-Border-Right: [ ]
  PlayerInventory-Border-Middle: [ ]

RegisterCommands:
  openMenus:
    aliases: [ ]
    permission: null
    execute:
      - 'tell: &7Argument `example` Required!'
    arguments:
      example: 'open: example'

```

**Comment by CCBlueX666** [comment]
与https://github.com/TrPlugins/TrMenu/issues/376#issue-1282573856重复
