### ISSUE TITLE
[问题]: 

### ISSUE THREAD

**Issue by DenNotFound** [TrPlugins/TrMenu#391]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-11-13 11:40:19)

| Server OS: Windows Server 2022 amd64 10.0
| Server software: git-Purpur-1826 (MC: 1.19.2) (1.19.2-R0.1-SNAPSHOT)
| Java version: 17.0.4

| TrMenu: 3.1.16
Installed Plugins: 
· AncientGates - 2.5.1 (0 KB)
· BetterMelon - 1.4.0 (0 KB)
· BossShopPro - 2.0.9 (0 KB)
· ChestSort - 13.2.0 (0 KB)
· Civs - 1.10.2 (0 KB)
· CurrentTime - 1.0.1 (0 KB)
· DeadlyDisasters - 12.4 (0 KB)
· DelayTeleport - 1.0.1 (0 KB)
· DenPlugin - 1.1.4 (0 KB)
· EliteMobs - 8.3.0 (0 KB)
· EnderDragon - 1.7.3 (0 KB)
· Essentials - 2.20.0-dev+17-6e931b2 (0 KB)
· EssentialsSpawn - 2.20.0-dev+17-6e931b2 (0 KB)
· ExcellentEnchants - 3.2.7 (0 KB)
· HolographicDisplays - 3.0.0-SNAPSHOT-b225 (0 KB)
· HungerKeeperPlus - 1.4.1 (0 KB)
· ILoreEdit - 2.5.1 (0 KB)
· InteractionVisualizer - 1.18.1.2 (0 KB)
· JulyLibrary - 2.6.0 (0 KB)
· JulySafe - 3.0.8 (0 KB)
· Kingdoms - 1.14.17 (0 KB)
· Kingdoms-Addon-Map-Viewers - 1.1.2 (0 KB)
· LiteSignIn - 1.6.0 (0 KB)
· LoneLibs - 1.0.21 (0 KB)
· LuckPerms - 5.4.40 (0 KB)
· MMOItems - 6.8.2 (0 KB)
· MiaoBoard - 2.6.0-git-00db90be472bcc688847491a33f195cc5637bbd1 (0 KB)
· MinePay - Release 2.6.16 (0 KB)
· Multiverse-Core - 4.3.2-SNAPSHOT-b870 (0 KB)
· Multiverse-NetherPortals - 4.2.2-b807 (0 KB)
· MythicLib - 1.4.2 (0 KB)
· NexEngine - 2.2.6 build-04/10/2022 (0 KB)
· Pl3xMap - 1.0.0-BETA-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.11.2 (0 KB)
· PlayerPoints - 3.2.4 (0 KB)
· PlayerTitle - 2.10.8 (0 KB)
· PlugManX - 2.3.0 (0 KB)
· ProtocolLib - 5.0.0-SNAPSHOT-b569 (0 KB)
· QuickShop - 5.1.0.9 (0 KB)
· Shopkeepers - 2.16.0 (0 KB)
· SkinsRestorer - 14.2.1 (0 KB)
· TAB - 3.1.5 (0 KB)
· TileDataSaver - 1.0.10 (0 KB)
· TrChat - 2.0.0-RC-3 (0 KB)
· TrMenu - 3.1.16 (0 KB)
· TrackingCompass - 1.1-SNAPSHOT (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VeinMiner - 1.17.10 (0 KB)
· WorldEdit - 7.2.11-beta-01+6200-0877589 (0 KB)
· WorldGuard - 7.0.7+216b061 (0 KB)
· XConomy - 2.18.14 (0 KB)
· eBackup - 1.3.1 (0 KB)
· spark - 1.9.45 (0 KB)
```

### 🔍 详细的描述

```
1. 启动服务器

```

### 🗄 服务端日志

```
[09:53:41] [Server thread/INFO]: [TrMenu-3.1.16.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib-common:1.6.21
[09:53:41] [Server thread/INFO]: [TrMenu-3.1.16.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib:1.6.21
[09:53:41] [Server thread/INFO]: [TrMenu-3.1.16.jar] Loading library org.jetbrains:annotations:13.0
[09:53:41] [Server thread/INFO]: [TrMenu-3.1.16.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21
[09:53:41] [Server thread/INFO]: [TrMenu-3.1.16.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21
[09:53:41] [Server thread/WARN]: [TrMenu] Loaded class com.electronwill.nightconfig.core.ConfigFormat from TrChat v2.0.0-RC-3 which is not a depend or softdepend of this plugin.
[09:53:42] [ForkJoinPool.commonPool-worker-14/INFO]: [TrMenu-3.1.16.jar] Loading library com.mongodb:MongoDB:3.12.2
[09:53:42] [ForkJoinPool.commonPool-worker-2/INFO]: [TrMenu-3.1.16.jar] Loading library org.openjdk.nashorn:nashorn-core:15.3
[09:53:42] [ForkJoinPool.commonPool-worker-2/INFO]: [TrMenu-3.1.16.jar] Loading library org.ow2.asm:asm-commons:7.3.1
[09:53:42] [ForkJoinPool.commonPool-worker-2/INFO]: [TrMenu-3.1.16.jar] Loading library org.ow2.asm:asm-tree:7.3.1
[09:53:42] [ForkJoinPool.commonPool-worker-2/INFO]: [TrMenu-3.1.16.jar] Loading library org.ow2.asm:asm:7.3.1
[09:53:42] [ForkJoinPool.commonPool-worker-2/INFO]: [TrMenu-3.1.16.jar] Loading library org.ow2.asm:asm-util:7.3.1
[09:53:43] [Server thread/ERROR]: Could not load 'plugins\TrMenu-3.1.16.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:158) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:417) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:325) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:468) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:154) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 7 more
Caused by: java.lang.NullPointerException: Cannot read field "next" because "this.next" is null
	at java.util.LinkedList$ListItr.next(LinkedList.java:897) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.inject.VisitorGroup.get(VisitorGroup.java:37) ~[TrMenu-3.1.16.jar:?]
	at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.visitStart(VisitorHandler.java:106) ~[TrMenu-3.1.16.jar:?]
	at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:99) ~[TrMenu-3.1.16.jar:?]
	at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:64) ~[TrMenu-3.1.16.jar:?]
	at me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:150) ~[TrMenu-3.1.16.jar:?]
	at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:37) ~[TrMenu-3.1.16.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:154) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 7 more
```

### ⚙ 配置文件

```

```

**Comment by JinOuYongGu** [comment]
完全一致的问题，偶尔会发生此情况
